//  Product find Constants

export const PRODUCT_FIND_REQUEST = "PRODUCT_FIND_REQUEST";
export const PRODUCT_FIND_SUCCESS = "PRODUCT_FIND_SUCCESS";
export const PRODUCT_FIND_ERR = "PRODUCT_FIND_ERR ";

//  Product findOne Constants

export const PRODUCT_FINDONE_REQUEST = "PRODUCT_FINDONE_REQUEST";
export const PRODUCT_FINDONE_SUCCESS = "PRODUCT_FINDONE_SUCCESS";
export const PRODUCT_FINDONE_ERR = "PRODUCT_FINDONE_ERR ";
